name: Verify Build

on:
  push:
    branches: [ jdk21 ]
  pull_request:
    branches: [ jdk21 ]

jobs:
  test-on-ubuntu:
    name: Run zip4j tests on ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
